apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pccs-tls-cert
spec:
  secretName: pccs-tls
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
    - my-app.example.com
  commonName: my-app.example.com
  privateKey:
    algorithm: RSA
    size: 2048
