apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | default "pccs" }}
  annotations:
    cert-manager.io/issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: ingress-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
    {{ $releaseName := .Release.Name | default "pccs" }}
    {{ range .Values.ingress.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}
            port:
              number: {{ $.Values.service.port }}
    {{ end }}
