apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | default "pccs"  }}
  labels:
    app: {{ .Release.Name | default "pccs"  }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name | default "pccs"  }}
