{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | default "pccs" }}
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- if or .Values.ingress.annotations (eq .Values.ingress.className "nginx") }}
  annotations:
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "pccs.ingressTlsSecret" . }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- $releaseName := .Release.Name | default "pccs" }}
{{- range .Values.ingress.paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
{{- end }}
