apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | default "pccs"  }}
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pccs-https-port
      protocol: TCP
  selector:
    {{- include "pccs.selectorLabels" . | nindent 4 }}
