{
 "title": "PCCS",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "PCCS response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PCCS storage usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"pccs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCCS CPU usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container=\"pccs\"}[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCCS memory usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PCCS storage usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"pccs.*\"} / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCCS memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"pccs\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCCS CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 22 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container=\"pccs\"}[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}