apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
  endpoints:
    - port: http
      interval: 30s
      path: /probe
      params:
        module: [http_2xx]
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: pccs-probe
  namespace: monitoring
spec:
  jobName: pccs
  prober:
    url: http://blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: https_2xx
  targets:
    staticConfig:
      static:
        - https://pccs-ingress-nginx-controller.pccs.svc.cluster.local/health/live
